FROM golang:alpine

RUN apk add --update nodejs npm
RUN npm update -g
RUN npm install -g yarn

WORKDIR /usr/app
COPY go.mod .
RUN go mod download

WORKDIR /usr/app/ui
COPY /ui/package.json package.json
COPY /ui/yarn.lock yarn.lock
RUN yarn install

COPY /ui .
RUN yarn build

WORKDIR /usr/app

COPY main.go .
RUN go build -o server

CMD ["./server"]